### ISSUE TITLE
test hygiene: 37 pre-existing frontend failures (browserless e2e + order-dependent flakes)

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#279]
Three independent lanes reported the same census tonight: the full frontend bun test run carries ~37 pre-existing failures — Playwright e2e specs failing structurally when no browser is present, plus order-dependent unit flakes that pass in isolation (ambient-music lifecycle, lootbox-retry-guard among them), alongside pre-existing typecheck errors (boot_shim, CharacterSwitcher, a missing types/chain module). None block CI (the matrix legs are scoped) but they poison local full-suite signal and every lane pays a triage tax. One cleanup lane: quarantine e2e specs behind an explicit browser-present gate (honest SKIP, never fail), fix or isolate the order-dependent flakes, resolve the typecheck errors. SKIP≠PASS law applies — quarantines carry reasons.
- [ ] a `src/game/screens/hud/world` suite leaks a partial engine `context` stub PROCESS-WIDE (9 whole-suite failures in unrelated files: `context.dispatch is not a function`) — the order-dependence class; scope the stub or restore in afterAll · found by the #2178 lane 08-05

**Comment by Sceat** [comment]
REPURPOSED AS THE TEST-DEBT EPIC (board-truth sweep): the family folds here —
- [ ] The ~37 browserless-e2e + order-dependent flakes quarantined honestly (this row's original ask)
- [ ] CI matrix legs still exit-0-swallowing engine/frontend red — the lying-green (was #125)
- [ ] Deterministic test failures pair (was #156)
- [ ] Suite parallelism/timeout hygiene (was #136)
- [ ] Coverage floor ratchets (was #48)
- [ ] Mutation-testing loop arming (was #50)

**Comment by Sceat** [comment]
EPIC FOLD (deflation sweep):
- [ ] click_cell verifies its own landing (was #58)
- [ ] Headless harness acceptance pack (was #57)
- [ ] Driven fight learns the recovery verb (was #56)
- [ ] Driven-fight variety: one driven row per spell class (was #7)
- [ ] 5 world-gen/lighting tests timeout under heavy load (was #198)
- [ ] Bun segfault in the world-shell suite — get_mob_template re-export (was #205)
- [ ] typecheck red on untouched edge: tactical tests + marketplace chain-type imports (was #354)
- [ ] .jsx files match no eslint block — the FP constitution is blind on React components (was #356)
- [ ] Three durable regression rows (was #49)
- [ ] Data-only test fixtures, re-export endgame (was #39)
- [ ] Gate-debt burn-down, mechanical (was #23)
- [ ] CodeQL local gate: container self-limits + wall-time pricing (was #193, #35)
- [ ] rpc/api suite wired into CI without undocumented local infra (was #318)

**Comment by Sceat** [comment]
Weapon-door lane adds to the flake ledger (all pass in isolation, memory-pressure timing class): 1× sim carve_world_arena, ~6× frontend (music/viewport/claims/runeforge). Same umbrella as the existing 37.

**Comment by Sceat** [comment]
Four more rows for the order-dependent ledger (reproduced on clean edge under a combined fight+data+components run; each passes isolated): icon slug map loader (#160) absent-blob degrade + its dedup case, spell corpus loader (#106) absent-blob degrade + its dedup case — a module-global manifest/walrus seam warmed by earlier suites defeats their cold-state fixtures.

**Comment by Sceat** [comment]
BATCH FOLD (board deflation), verbatim: - [ ] #527 three pre-existing red rows on edge (ambient_music lifecycle +) · - [ ] #562 5 unconditional skips cite superseded #291 · - [ ] #568 fight_trace_tee no longer isolates a faulting tap · - [ ] #569 crush_item sibling-kiosk PTB test · - [ ] #589 crush_actions order-dependence (full-suite only) · - [ ] #587 read_templates.test.js hits live testnet by default

**Comment by Sceat** [comment]
FOLD +1: - [ ] #588 trace_tap.js unconditional msg.fight_id read breaks on poisoned getters (#646 family)

**Comment by Sceat** [comment]
Census refresh against the current tree — the frontend full-suite failure count is down from ~37 to **1**, and the survivor is a different shape than anything folded here.

CI-exact invocation (`cd packages/frontend && bun run test`), three consecutive runs:

```
4007 pass · 204 skip · 1 fail   (x3, identical)
```

The e2e-without-a-browser class and the order-dependent flakes named in the body are gone: both #662 (`dungeon_run_honest_surface`) and #663 (`embed_voxel_fight_camera` SETTLE azimuth) pass in all three runs and have been closed on that evidence.

FOLD +1 — the one survivor, stable rather than order-dependent:
- [ ] `src/simulator/persistence.test.ts` — the IndexedDB-failure case leaks its injected `quota exceeded` error out of the `queueMicrotask` callback, so the deliberate failure path fails the suite instead of being asserted on.

**Comment by Sceat** [comment]
Live specimen for the order-dependence class, caught in the wild 2026-08-06: `ambient_music.js` keeps module-scope playback state (`started`, `roam`, `battle`) across test files in the one-process suite run. Bun 1.3.14 (CI, unpinned — #2272) changed file execution order vs 1.3.5 (dev), so an earlier file left the engine started with its own stub elements and `hack_radio_remount.test.js` then hit the repoint branch on them: `TypeError: roam.load is not a function`, red-gating PR #2271 while every file passes green in isolation on both runtimes. Cure applied per house precedent: a `_reset_ambient_music_for_test` door called in afterEach (riding the train). Classifier note for this census: module-scope latches in src are the leak source; a second specimen from the same module graduates it to the one-reducer audit family.

**Comment by Sceat** [comment]
Full-population census at edge b73b7dcfb (2026-08-06), every package suite run: the pre-existing-failure population this row was filed to classify is **gone**. Tallies — engine 2031/0 · frontend 5558/0 · fight 1329/0 · sdk 619/0 · world 175/0 · party 80/0 · inventory 57/0 · sim 996/**2** — and both sim failures are timeout-shaped with the wall-clock marker (`carve_world_arena` board-dims + connectivity sweeps, 5.4s/5.8s against the 5s default), i.e. the #830 class already tracked as its box 1 (#806). Zero order-dependence, zero browserless, zero assertion-shaped failures anywhere. The drain happened via today's landings (the ambient reset-door + the measured wall-clock budgets). Classification deliverable complete; the two survivors are owned by #830. Closing.

**Comment by Sceat** [comment]
Closed on the census above: the classification is the deliverable, the population is two known-class timeouts owned by #830 box 1.
